### ISSUE TITLE
regressions when upgrading Adafruit TinyUSB Library to 3.1.0

### ISSUE THREAD

**Issue by delan** [delan/usb3sun#13]
- usb3sun d59f48b6d3e4939538a4ba5fd8dfc1c40b121cac
- Microsoft Wired Keyboard 600 (045E:0750)

[Adafruit TinyUSB Library](https://github.com/adafruit/Adafruit_TinyUSB_Arduino)
- 2.0.1 = works
- 3.1.0 = adafruit/Adafruit_TinyUSB_Arduino#296
- successful workaround in [tinyusb3.patch.txt](https://github.com/delan/usb3sun/files/14480101/tinyusb3.patch.txt)

status of other patches with 3.1.0
- [tinyusb1.patch](https://github.com/delan/usb3sun/blob/d59f48b6d3e4939538a4ba5fd8dfc1c40b121cac/tinyusb1.patch) is definitely no longer required
- [tinyusb2.patch](https://github.com/delan/usb3sun/blob/d59f48b6d3e4939538a4ba5fd8dfc1c40b121cac/tinyusb1.patch) seems to no longer be required?
  - we should bisect and figure out why
  - 2.2.2 = required
  - 2.2.3 = not required
- we need to update [debug1.patch](https://github.com/delan/usb3sun/blob/d59f48b6d3e4939538a4ba5fd8dfc1c40b121cac/debug1.patch) → [debug1.patch.txt](https://github.com/delan/usb3sun/files/14480123/debug1.patch.txt)
  - `#include <Arduino.h>` in Adafruit_TinyUSB.h now yields “undefined reference to _ZN17Adafruit_USBD_CDC16getInstanceCountEv”
  - moving the declaration to the local Adafruit_TinyUSB_API.h in .pio doesn’t work, we need to patch the copy in ~/.platformio/packages/framework-arduinopico
  - using HardwareSerial in declaration now yields “'HardwareSerial' does not name a type” due to circular include
- we now need [debug3.patch.txt](https://github.com/delan/usb3sun/files/14480120/debug3.patch.txt)
  `git -C ~/.platformio/packages/framework-arduinopico apply $PWD/debug3.patch`
